using System.Runtime.InteropServices;
using System.Reflection;
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("Reinforced.Lattice.Mvc4.Razor")]
[assembly: AssemblyDescription("Razor extensions for Reinforced.Lattice and ASP.NET MVC 4")]
[assembly: AssemblyCompany("Reinforced Software Construction")]
[assembly: AssemblyProduct("Reinforced.Lattice")]
[assembly: AssemblyCopyright("(c) 2017 Pavel B. Novikov")]
[assembly: ComVisible(false)]

