//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
var PowerTables;
(function (PowerTables) {
    /** Ordering */
    (function (Ordering) {
        /** Ascending */
        Ordering[Ordering["Ascending"] = 0] = "Ascending";
        /** Descending */
        Ordering[Ordering["Descending"] = 1] = "Descending";
        /** Ordering is not applied */
        Ordering[Ordering["Neutral"] = 2] = "Neutral";
    })(PowerTables.Ordering || (PowerTables.Ordering = {}));
    var Ordering = PowerTables.Ordering;
})(PowerTables || (PowerTables = {}));
//# sourceMappingURL=Interfaces.js.map